config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "upload_excel#show"
  get 'upload_excel/show'
 
  post 'excel/send_data' => 'upload_excel#get_data'
  get 'excel/show' => 'upload_excel#show'
  post 'excel/delete' => 'upload_excel#delete_data'
  get 'excel/download' => 'upload_excel#download'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email_id, :first_name, :last_name
    require 'roo'
	# To import data using csv file and saving in database 
    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

    def self.import(file)
      @errors = []
      data = open_spreadsheet(file)
       # open spreadsheet
      data.sheets.each do |num|
        data.sheet(num)
        headers = data.row(1) # get header row
        data.each_with_index do |row, idx|
          next if idx == 0 # skip header row
          # create hash from headers and cells
          user_data = Hash[[headers, row].transpose]
          # next if user exists
          if User.exists?(email_id: user_data['email_id'])
            puts "User with email #{user_data['email_id']} already exists"
            next
          end
          
          user = User.new(user_data)
          puts "Saving User with email '#{user.email_id}'"
          if user.save
          else
          user.errors.full_messages.each do |message|
              @errors << "Row #{idx} - #{message}, Number of Sheets - #{data.sheets.count}, Total Row - #{data.last_row}"
            end
          end
        end
      end
      @errors
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :flash_class
	 def flash_class(level)
      case level
        when 'notice' then "alert alert-info"
        when 'success' then "alert alert-success"
        when 'error' then "alert alert-danger"
        when 'alert' then "alert alert-warning"
      end
    end
end

app/controllers/upload_excel_controller.rb
class UploadExcelController < ApplicationController

def index
end

#to get data from csv file 
def get_data 
	# import method written in model 
	import_user = User.import(params[:user][:file])
	if import_user == []
		flash[:notice] = "Users uploaded successfully"
		redirect_to excel_show_path
	else
		sheet = []
		validation = []
		total_row = []
		sheet << import_user[0].split(",")[1]
		total_row << import_user[0].split(",")[2]
		import_user.each do |data|
			validation << data.split(",")[0].split("-")[0] + "-" + data.split(",")[0].split("-")[1]
		end
		flash[:notice] = "#{sheet} , #{validation}, #{total_row}"
		redirect_to excel_show_path
	end
end

#show the data from database 
def show 
	@data = User.all
end

 #To delete entry from database 
def delete_data	
	delete_data = params[:delete_users][:data].split(" ")
	User.where(id: delete_data).destroy_all
	redirect_to excel_show_path
end

# # to download data as csv file 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadExcel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
        <% flash.each do |key, value| %>
          <% if value.to_s != 'true' %>
            <div class="<%= flash_class(key)%> alert-dismissible">
              <%= value %>
            </div>
          <% end %>
        <% end %>
      </div>
    <%= yield %>
  </body>
</html>
<!-- <script type="text/javascript">
  $('document').ready(function() {
  setTimeout(function() {
    $('#flash').slideUp();
  }, 3000);
});
  $(".alert" ).fadeOut(5000);
   $(".alert-success" ).fadeOut(5000);
   $(".alert-danger" ).fadeOut(5000);
</script -->

app/views/upload_excel/show.html.erb
<!-- Form to give upload botton for csv -->
<%= form_with scope: :user, url: excel_send_data_path , local: true do |form| %>
	
	<p>
		<%= form.label :file %><br>
		<%= form.file_field :file %>
	</p>

	<p>
		<%= form.submit %>
		</p>
<% end %>
<% if @errors %>
  <% @errors.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<html>
<head>
    <!-- plugin and cdn from dataatble.net to add jquery datatable -->
<link rel="stylesheet"  href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script  src ="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script >
<script type="text/javascript">
$(document).ready( function () {
    $('#myTable').DataTable();
} );
</script>
</head>

<table id="myTable" class="display">
    <thead>
        <tr>
        	<th></th>
            <th>First Name</th>
            <th>last Name</th>
            <th>Email Id </th>
        </tr>
    </thead>
    <tbody>
    	<% @data.each do |data| %>
        <tr>
        	 <td><input type="checkbox" value="<%= data.id%>" class="delete-user" id="<%=data.id %>"></td>
            <td><%= data.first_name%></td>
            <td><%= data.last_name%></td>
            <td><%= data.email_id %></td>
        </tr>
        <%end%>
    </tbody>
</table>
<!-- Delete button -->
<%= form_with scope: :delete_users, url: excel_delete_path , local: true do |form| %>
    <p>
        <%= form.hidden_field :data , id: "duser" %>
    </p>

    <p>
        <%= form.submit  'Delete Selected' %>
    </p>
<% end %>

<script type="text/javascript">
// to pass the selected checkbox data to params
    $('.delete-user').on('click', function (argument) {
      if($(this).prop('checked') == true){
    $('#duser').val($('#duser').val()+" "+this.id);
}else{
    var array = $('#duser').val().split(" ")
    var index = array.indexOf(this.id);
if (index > -1) {
  array.splice(index, 1);
  $('#duser').val(array.join(" "));
}

}
      
    })
</script>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>